CASMTRIAGE-3326 simplify clock skew check by using a chronyc command
Cray-HPE/csm-testing pull request #312
Opened 2022-05-13 18:18 UTC by jacobsalmela

Signed-off-by: Jacob Salmela <jacob.salmela@hpe.com>

## Summary and Scope

Dramatically simplifies the clock skew test by running a chronyc command.

This command waits until the node is in sync.  In this test, I check every 10 seconds, timing out after a minute and allowing for skew of 0.1ms.

This does away with all the SSH stuff and just talks directly to chrony to see if it thinks it is in sync.

## Issues and Related PRs

* Resolves CASMTRIAGE-3326'

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `hela`

### Test description:

## Risks and Mitigations

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-05-16 13:48 UTC, heemstra approved these changes

2022-05-16 21:02 UTC, rustydb approved these changes

2022-05-17 15:22 UTC, mharding-hpe requested changes
Is there a reason we wouldn't want to log the output of the command? It seems like that could be useful, particularly in the case of a failure.

2022-05-17 15:22 UTC, mharding-hpe commented on goss-testing/tests/ncn/goss-check-clock-skew.yaml
>  command:
```suggestion
{{ $scripts := .Env.GOSS_BASE | printf "%s/scripts" }}
{{ $logrun := $scripts | printf "%s/log_run.sh" }}
command:
```

2022-05-17 15:22 UTC, mharding-hpe commented on goss-testing/tests/ncn/goss-check-clock-skew.yaml
> +    exec: "chronyc waitsync 6 0.5 0.5 10"
```suggestion
        exec: |-
            "{{$logrun}}" -l "{{$testlabel}}" \
                /usr/bin/chronyc waitsync 6 0.5 0.5 10
```

2022-05-17 15:22 UTC, mharding-hpe commented on goss-testing/tests/ncn/goss-check-clock-skew.yaml
> +  check_clock_skew:
```suggestion
    {{ $testlabel := "check_clock_skew" }}
    {{$testlabel}}:
```

2022-05-17 15:27 UTC, mharding-hpe requested changes
Should this PR also delete the current clock skew shell script, since no tests are using it any longer?

2022-05-17 15:54 UTC, jacobsalmela commented on goss-testing/tests/ncn/goss-check-clock-skew.yaml
>  command:
Fixed, scripts dir isn't needed

2022-05-17 15:54 UTC, jacobsalmela commented on goss-testing/tests/ncn/goss-check-clock-skew.yaml
> +    exec: "chronyc waitsync 6 0.5 0.5 10"
Fixed

2022-05-17 15:55 UTC, jacobsalmela commented on goss-testing/tests/ncn/goss-check-clock-skew.yaml
> +  check_clock_skew:
fixed

2022-05-17 16:22 UTC, mharding-hpe commented
Also need a main branch PR for this.

2022-05-17 16:28 UTC, merged

2022-05-17 17:04 UTC, jacobsalmela commented
@mharding-hpe https://github.com/Cray-HPE/csm-testing/pull/315