CASMPET-5620 Add additional TLS tests
Cray-HPE/csm-testing pull request #357
Opened 2022-08-08 19:24 UTC by kburns-hpe

## Summary and Scope

Adds tests to validate that the platform CA is included in the ca-bundle.pem and that a new version of certifi has not been installed.

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [CASMPET-5620](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5620)

## Testing

### Tested on:

  * Shandy

### Test description:

Validated that goss tests passed on systems setup correctly and failed when modified.

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why? Y
- Was upgrade tested? If not, why? N, new tests.
- Was downgrade tested? If not, why? N, new tests.
- Were new tests (or test issues/Jiras) created for this change? Y

## Risks and Mitigations

## Pull Request Checklist

- [X] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [X] License file intact
- [X] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-08-08 20:26 UTC, rgross727 approved these changes

2022-08-09 17:20 UTC, mharding-hpe requested changes

2022-08-09 17:20 UTC, mharding-hpe commented on goss-testing/tests/ncn/goss-platform-ca-in-bundle.yaml
> +# (C) Copyright 2014-2022 Hewlett Packard Enterprise Development LP
```suggestion
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
```

2022-08-09 17:20 UTC, mharding-hpe commented on goss-testing/tests/ncn/goss-validate-certifi-version.yaml
> +# (C) Copyright 2014-2022 Hewlett Packard Enterprise Development LP
```suggestion
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
```

2022-08-09 17:20 UTC, mharding-hpe commented on goss-testing/tests/ncn/goss-validate-certifi-version.yaml
> +command:
May as well log the output of this test.

```suggestion
{{ $logrun := .Env.GOSS_BASE | printf "%s/scripts/log_run.sh" }}
command:
```

2022-08-09 17:20 UTC, mharding-hpe commented on goss-testing/tests/ncn/goss-validate-certifi-version.yaml
> +  validate_certifi_version:
```suggestion
  {{ $testlabel := "validate_certifi_version" }}
  {{$testlabel}}:
```

2022-08-09 17:20 UTC, mharding-hpe commented on goss-testing/tests/ncn/goss-validate-certifi-version.yaml
> +    exec: "pip show certifi"
```suggestion
    exec: |-
      "{{$logrun}}" -l "{{$testlabel}}" \
        pip show certifi
```

2022-08-09 17:20 UTC, mharding-hpe commented on goss-testing/tests/ncn/goss-validate-certifi-version.yaml
> +      desc: "If this fails then validate that an upstream version of certifi has not been installed. If a non-SLES certifi package has been installed the uninstall it by running `pip uninstall certif
```suggestion
      desc: "If this fails, then validate that an upstream version of certifi has not been installed. If a non-SLES certifi package has been installed, then uninstall it by running `pip uninstall certifi`."
```

2022-08-09 19:02 UTC, rgross727 approved these changes

2022-08-09 23:47 UTC, mharding-hpe approved these changes

2022-08-10 21:22 UTC, merged