CASMPET-5559 Update spire-bss test description
Cray-HPE/csm-testing pull request #358
Opened 2022-08-08 19:52 UTC by kburns-hpe

## Summary and Scope

Update the spire bss test description so that it tells the user to recreate the spire bss job if it fails.

## Issues and Related PRs

* Resolves [CASMPET-5559](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5559)

## Testing

### Tested on:

  * shandy

### Test description:

Validated test still worked properly

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why? Y 
- Was upgrade tested? If not, why? N
- Was downgrade tested? If not, why? N
- Were new tests (or test issues/Jiras) created for this change? N

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [X] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-08-08 19:55 UTC, bklei approved these changes

2022-08-08 20:17 UTC, rgross727 approved these changes

2022-08-09 17:23 UTC, mharding-hpe requested changes

2022-08-09 17:23 UTC, mharding-hpe commented on goss-testing/tests/ncn/goss-spire-bss-metadata-exist.yaml
> +      desc: If this test fails then you need to recreate the spire-update-bss-# job in the spire namespace so that it adds the spire information to the meta-data service.
```suggestion
      desc: If this test fails, then recreate the spire-update-bss-# job in the spire namespace. The job will add the Spire information to the meta-data service.
```

2022-08-09 23:47 UTC, mharding-hpe approved these changes

2022-08-10 21:17 UTC, merged